---
- hosts: localhost
  tasks:
    - name: add hosts
      add_host:
        #name: "{{ vm['instances'][0]['private_ip_address'] }}"
        name: "{{private_ip}}"
        groups: created_nodes
        ansible_user: "ubuntu"
        ansible_connection: "ssh"
        ansible_ssh_private_key_file: "{{private_key_path}}"
- hosts: created_nodes
  become: yes 
  remote_user: ubuntu
  vars:
    http_port: 80
  tasks:
    - name: Wait for SSH banners
      wait_for_connection:
        delay: 5
        timeout: 30000

    - name: Check Update
      apt:
        update_cache: yes

    - apt: name=apache2 update_cache=yes state=present
    
    - debug: var=ansible_facts
