name: Install wget and unzip

on: [push]

jobs:
  install_dependencies:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, centos-latest]

    steps:
      - name: Set up environment
        run: |
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            if [ -f /etc/os-release ]; then
              . /etc/os-release
              case "$ID" in
                ubuntu)
                  sudo apt-get update
                  sudo apt-get install -y wget unzip
                  ;;
                rhel | centos)
                  sudo yum install -y wget unzip
                  ;;
              esac
            fi
          fi

