- hosts: all
  become: yes
  vars:
    http_port: 80
  tasks:
  - name: install apache2
    yum: name=httpd update_cache=yes state=present
  - name: start apache2
    service: name=httpd state=started
  #- name: install apache2
  #  apt: name=apache2 update_cache=yes state=present
  #- name: start apache2
  #  service: name=apache2 state=started
    
