- hosts: 10.198.252.219
  remote_user: ec2-user
  #ansible_ssh_private_key_file: /home/cmpdev/valar-ansible-rsa.pem
  become: yes
  tasks:
  - name: Install httpd
    package:
      name: httpd
      state: present
