- hosts: all
  become: yes
  tasks:
    - name: Stop apache2 service
      service: name=apache2 state=stopped
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: stop the httpd service
      service: name=httpd state=stopped
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat'
