---
- hosts: all
  become: yes
  tasks:
    - name: Stop apache2 service
      service: name=apache2 state=stopped
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Uninstall apache2 service
      yum: name=apache2 update_cache=yes state=absent
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Stop the httpd service
      service: name=httpd state=stopped
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat'

    - name: Uninstall httpd service
      yum: name=httpd update_cache=yes state=absent
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat'
